/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: ["class"],
  theme: {
    borderRadius: {
      sm: "0.25rem",
      base: "0.375rem",
      DEFAULT: "0.375rem",
      full: "9999px",
    },
    boxShadow: {
      DEFAULT: "0px 1px 3px 0px rgba(0, 0, 0, 0.04)",
      "sm+inner":
        "0px 1px 3px 0px rgba(0, 0, 0, 0.04), 0px 1px 0px 0px rgba(255, 255, 255, 0.08) inset",
    },
    colors: {
      white: "var(--color-white)",
      black: "var(--color-black)",
      transparent: "rgba(0,0,0,0)",
      blue: {
        "1": "var(--color-blue-1)",
        "2": "var(--color-blue-2)",
        "3": "var(--color-blue-3)",
        "4": "var(--color-blue-4)",
        "5": "var(--color-blue-5)",
        "6": "var(--color-blue-6)",
        "7": "var(--color-blue-7)",
        "8": "var(--color-blue-8)",
        "9": "var(--color-blue-9)",
        "10": "var(--color-blue-10)",
        "11": "var(--color-blue-11)",
        "12": "var(--color-blue-12)",
      },
      gray: {
        "1": "var(--color-gray-1)",
        "2": "var(--color-gray-2)",
        "3": "var(--color-gray-3)",
        "4": "var(--color-gray-4)",
        "5": "var(--color-gray-5)",
        "6": "var(--color-gray-6)",
        "7": "var(--color-gray-7)",
        "8": "var(--color-gray-8)",
        "9": "var(--color-gray-9)",
        "10": "var(--color-gray-10)",
        "11": "var(--color-gray-11)",
        "12": "var(--color-gray-12)",
      },
      green: {
        "1": "var(--color-green-1)",
        "2": "var(--color-green-2)",
        "3": "var(--color-green-3)",
        "4": "var(--color-green-4)",
        "5": "var(--color-green-5)",
        "6": "var(--color-green-6)",
        "7": "var(--color-green-7)",
        "8": "var(--color-green-8)",
        "9": "var(--color-green-9)",
        "10": "var(--color-green-10)",
        "11": "var(--color-green-11)",
        "12": "var(--color-green-12)",
      },
      pink: {
        "1": "var(--color-pink-1)",
        "2": "var(--color-pink-2)",
        "3": "var(--color-pink-3)",
        "4": "var(--color-pink-4)",
        "5": "var(--color-pink-5)",
        "6": "var(--color-pink-6)",
        "7": "var(--color-pink-7)",
        "8": "var(--color-pink-8)",
        "9": "var(--color-pink-9)",
        "10": "var(--color-pink-10)",
        "11": "var(--color-pink-11)",
        "12": "var(--color-pink-12)",
      },
      purple: {
        "1": "var(--color-purple-1)",
        "2": "var(--color-purple-2)",
        "3": "var(--color-purple-3)",
        "4": "var(--color-purple-4)",
        "5": "var(--color-purple-5)",
        "6": "var(--color-purple-6)",
        "7": "var(--color-purple-7)",
        "8": "var(--color-purple-8)",
        "9": "var(--color-purple-9)",
        "10": "var(--color-purple-10)",
        "11": "var(--color-purple-11)",
        "12": "var(--color-purple-12)",
      },
      red: {
        "1": "var(--color-red-1)",
        "2": "var(--color-red-2)",
        "3": "var(--color-red-3)",
        "4": "var(--color-red-4)",
        "5": "var(--color-red-5)",
        "6": "var(--color-red-6)",
        "7": "var(--color-red-7)",
        "8": "var(--color-red-8)",
        "9": "var(--color-red-9)",
        "10": "var(--color-red-10)",
        "11": "var(--color-red-11)",
        "12": "var(--color-red-12)",
      },
      yellow: {
        "1": "var(--color-yellow-1)",
        "2": "var(--color-yellow-2)",
        "3": "var(--color-yellow-3)",
        "4": "var(--color-yellow-4)",
        "5": "var(--color-yellow-5)",
        "6": "var(--color-yellow-6)",
        "7": "var(--color-yellow-7)",
        "8": "var(--color-yellow-8)",
        "9": "var(--color-yellow-9)",
        "10": "var(--color-yellow-10)",
        "11": "var(--color-yellow-11)",
        "12": "var(--color-yellow-12)",
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
      },
    },
    fontFamily: {
      body: ["Ronzino"],
      display: ["Ronzino"],
    },
    fontSize: {
      sm: "0.875rem",
      base: "1rem",
      md: "1.0625rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.75rem",
      "4xl": "2rem",
      "5xl": "2.25rem",
      "6xl": "2.5rem",
      "7xl": "2.75rem",
      "8xl": "3rem",
      "9xl": "3.25rem",
      "10xl": "3.5rem",
      "11xl": "3.75rem",
      "12xl": "4rem",
      "13xl": "4.25rem",
      "14xl": "4.5rem",
    },
    fontWeight: {
      normal: "400",
      medium: "500",
      bold: "600",
    },
    extend: {
      ringWidth: {
        "3": "3px",
      },
      screens: {
        lg: "912px",
        print: { raw: "print" },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
