/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: ["class"],
  theme: {
    borderRadius: {
      sm: "0.25rem",
      base: "0.375rem",
      DEFAULT: "0.375rem",
      full: "9999px",
    },
    boxShadow: {
      DEFAULT: "0px 1px 3px 0px rgba(0, 0, 0, 0.04)",
      "sm+inner":
        "0px 1px 3px 0px rgba(0, 0, 0, 0.04), 0px 1px 0px 0px rgba(255, 255, 255, 0.08) inset",
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
      },
    },
    fontFamily: {
      body: ["Ronzino"],
      display: ["Ronzino"],
    },
    fontSize: {
      sm: "0.875rem",
      base: "1rem",
      md: "1.0625rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.75rem",
      "4xl": "2rem",
      "5xl": "2.25rem",
      "6xl": "2.5rem",
      "7xl": "2.75rem",
      "8xl": "3rem",
      "9xl": "3.25rem",
      "10xl": "3.5rem",
      "11xl": "3.75rem",
      "12xl": "4rem",
      "13xl": "4.25rem",
      "14xl": "4.5rem",
    },
    fontWeight: {
      "400": "400",
      "450": "450",
      "500": "500",
      "550": "550",
      "600": "600",
      "700": "700",
    },
    extend: {
      colors: {
        gray: {
          "1": "var(--color-gray-1)",
          "2": "var(--color-gray-2)",
          "3": "var(--color-gray-3)",
          "4": "var(--color-gray-4)",
          "5": "var(--color-gray-5)",
          "6": "var(--color-gray-6)",
          "7": "var(--color-gray-7)",
          "8": "var(--color-gray-8)",
          "9": "var(--color-gray-9)",
          "10": "var(--color-gray-10)",
          "11": "var(--color-gray-11)",
          "12": "var(--color-gray-12)",
        },
        yellow: {
          "1": "var(--color-yellow-1)",
          "2": "var(--color-yellow-2)",
          "3": "var(--color-yellow-3)",
          "4": "var(--color-yellow-4)",
          "5": "var(--color-yellow-5)",
          "6": "var(--color-yellow-6)",
          "7": "var(--color-yellow-7)",
          "8": "var(--color-yellow-8)",
          "9": "var(--color-yellow-9)",
          "10": "var(--color-yellow-10)",
          "11": "var(--color-yellow-11)",
          "12": "var(--color-yellow-12)",
        },
        green: {
          "1": "#FBFEFC",
          "2": "#F2FCF5",
          "3": "#E9F9EE",
          "4": "#DDF3E4",
          "5": "#CCEBD7",
          "6": "#B4DFC4",
          "7": "#92CEAC",
          "8": "#5BB98C",
          "9": "#30A46C",
          "10": "#299764",
          "11": "#18794E",
          "12": "#153226",
        },
        red: {
          "1": "var(--color-red-1)",
          "2": "var(--color-red-2)",
          "3": "var(--color-red-3)",
          "4": "var(--color-red-4)",
          "5": "var(--color-red-5)",
          "6": "var(--color-red-6)",
          "7": "var(--color-red-7)",
          "8": "var(--color-red-8)",
          "9": "var(--color-red-9)",
          "10": "var(--color-red-10)",
          "11": "var(--color-red-11)",
          "12": "var(--color-red-12)",
        },
        purple: {
          "1": "var(--color-purple-1)",
          "2": "var(--color-purple-2)",
          "3": "var(--color-purple-3)",
          "4": "var(--color-purple-4)",
          "5": "var(--color-purple-5)",
          "6": "var(--color-purple-6)",
          "7": "var(--color-purple-7)",
          "8": "var(--color-purple-8)",
          "9": "var(--color-purple-9)",
          "10": "var(--color-purple-10)",
          "11": "var(--color-purple-11)",
          "12": "var(--color-purple-12)",
        },
        blue: {
          "1": "var(--color-blue-1)",
          "2": "var(--color-blue-2)",
          "3": "var(--color-blue-3)",
          "4": "var(--color-blue-4)",
          "5": "var(--color-blue-5)",
          "6": "var(--color-blue-6)",
          "7": "var(--color-blue-7)",
          "8": "var(--color-blue-8)",
          "9": "var(--color-blue-9)",
          "10": "var(--color-blue-10)",
          "11": "var(--color-blue-11)",
          "12": "var(--color-blue-12)",
        },
        yellow: {
          "9": "var(--color-yellow-9)",
          "10": "var(--color-yellow-10)",
          "11": "var(--color-yellow-11)",
        },
      },
      ringWidth: {
        "3": "3px",
      },
      screens: {
        lg: "912px",
        print: { raw: "print" },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
